select * from customer_shopping

--Q1. What is the total revenue generated by male vs. female customers
select gender ,SUM(purchase_amount) as revenue
from customer_shopping
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from customer_shopping
where discount_applied = 'Yes' AND purchase_amount >= (
	select AVG(purchase_amount) from customer_shopping
)

-- Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased,ROUND(avg(review_rating),2) as avg_product_rating
from customer_shopping
group by item_purchased
order by avg(review_rating) desc

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, avg(purchase_amount) avg_shipping
from customer_shopping
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,count(customer_id) as total_customers,
ROUND(avg(purchase_amount),2) as avg_spend,
ROUND(sum(purchase_amount),2) as total_revnue
from customer_shopping
group by subscription_status
order by total_revnue

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased,
ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
from customer_shopping
group by item_purchased
order by discount_rate desc


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with cte as(
select customer_id,previous_purchases,
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	END as customer_segment
from customer_shopping
)
select customer_segment,count(*) as 'no_of_customer'
from cte
group by customer_segment
order by no_of_customer desc


--Q8. What are the top 3 most purchased products within each category?
with cte as(
select category,item_purchased,
count(customer_id) as total_order,
row_number() over(partition by category order by count(customer_id) desc) as irn
from customer_shopping
group by category , item_purchased

)

SELECT irn,category, item_purchased, total_order
FROM cte
WHERE irn <=3;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers
from customer_shopping
where previous_purchases>5
group by subscription_status

--Q10. What is the revenue contribution of each age group? 
select age_group,sum(purchase_amount) as revnue
from customer_shopping
group by age_group